### ISSUE TITLE
Cancelling an order does not work

### ISSUE THREAD

**Issue by cymp** [lvcn1/ws-client-examples#16]
Dear Livecoin team,

I don't receive any CANCEL_LIMIT_ORDER_RESPONSE when Cancelling an order (placing works). I am setting the ID and the currencyPair in the LcWsApi.CancelLimitOrderRequest.Builder, but when I am sending the request to the websocket, the order is never cancelled (I looked on the UI) and I don't receive any CANCEL_LIMIT_ORDER_RESPONSE.

**Comment by michaeldim** [comment]
This is working fine for me with the Javascript library. Are you providing the id as a Int64 value and are you setting the expireControl parameter (this is not optional).  Are you also sure the request is not responding instead with an error; are you handling error messages?

**Comment by cymp** [comment]
Yes, I am using the Java library, I am providing a long for the id, I set the expireControl property (otherwise I get an exception), and I handle error messages. Thanks for your answer.

**Comment by cymp** [comment]
I just spotted a stupid mistake, that must be thanks to you...

**Comment by cymp** [comment]
The problem now is that I can cancel the order, but I still don't receive that CANCEL_LIMIT_ORDER_RESPONSE

**Comment by michaeldim** [comment]
When you send the message of type: CANCEL_LIMIT_ORDER you could try adding a token message to it such as 'cancelOrder'. Then check to see if wsResponseMessage.meta.token == 'cancelOrder'. If nothing is returned when you send the cancel request then I would say there is definitely an issue. If you do receive a message token back with 'cancelOrder' see what response.getMeta().getResponseType() equals.

**Comment by cymp** [comment]
Well, I already tried that: I am logging all of the LcWsApi.WsResponse messages I receive, and I tried to add a token to the CANCEL_LIMIT_ORDER  message the same way you suggested. I couldn't receive any message containing this token. 

Have you managed to catch a cancel response?

**Comment by michaeldim** [comment]
Yeh I receive these messages from the websocket server using Javascript client, so that makes me think it might be something in the Java library that is the issue.

**Comment by dkpostwww** [comment]
Dear @cymp, can you provide piece of your code sending cancel request? This can help a lot.

**Comment by cymp** [comment]
Sure:
![image](https://user-images.githubusercontent.com/3685318/46934947-d17b8500-d059-11e8-9031-0fdcc4438ff7.png)
![image](https://user-images.githubusercontent.com/3685318/46934981-f112ad80-d059-11e8-8a27-fc1e90ce8016.png)

**Comment by dkpostwww** [comment]
Seems like we have fixed it. Can you try once more?

**Comment by cymp** [comment]
Cancel is effective, but I still don't receive any CANCEL_LIMIT_ORDER message.

**Comment by cymp** [comment]
@dkpostwww would you have any update regarding this please?

**Comment by cymp** [comment]
Looks like it works now, took some time to work on prod, thanks.
